# -*- coding: utf-8 -*-
"""cli_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10y6EcH_9jM3XkLA3dkp3k3nwWfKTt8Hr
"""

import pickle

# Load saved model & vectorizer
import joblib
model = joblib.load("model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

print("📩 SMS Spam Classifier")
print("-----------------------")
while True:
    msg = input("\nEnter a message (or 'exit' to quit): ")
    if msg.lower() == "exit":
        break
    msg_tfidf = vectorizer.transform([msg])
    pred = model.predict(msg_tfidf)[0]
    print("Prediction:", "Spam 🚨" if pred == 1 else "Ham ✅")